VTU/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vtp.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vtp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    # path('logout/', views.logoutUser, name="logout"),


    path('', views.dashboard, name="dashboard"),
    path('dataform/', views.dataform, name='dataform'),
    path('<int:pk>/', views.person_update_view, name='person_change'),

    path('ajax/dataplan/', views.datatypes, name='dataplan'),
    path('ajax/load-datatypes/', views.datatypes, name='ajax_load_datatypes'), # AJAX


    path('airtimeform/', views.airtimeform, name='airtimeform'),
]

vtp/models.py
from django.db import models

from django.contrib.auth.models import User


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200)

    def __str__(self):
        return self.name
class Network(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Datatype(models.Model):
    network = models.ForeignKey(Network, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Dataplan(models.Model):
    network = models.ForeignKey(Network, on_delete=models.CASCADE)
    datatype = models.ForeignKey(Datatype, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name

class Permode(models.Model):
    network = models.ForeignKey(Network, on_delete=models.SET_NULL, blank=True, null=True)
    name = models.CharField(max_length=124)
    datatype = models.ForeignKey(Datatype, on_delete=models.SET_NULL, blank=True, null=True)
    dataplan = models.ForeignKey(Dataplan, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.name
    


          # ....AIRTIME MODELS....


class Airtime(models.Model):
    airtime = models.CharField(max_length=40)

    def __str__(self):
        return self.airtime



class AirtimeTran(models.Model):
    airtime = models.ForeignKey(Airtime, on_delete=models.SET_NULL, blank=True, null=True)
    number = models.CharField(max_length=124)
    amount = models.CharField(max_length=124)

    def __str__(self):
        return self.number

vtp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from vtp.models import Permode, Datatype, AirtimeTran, Airtime



            # .... VALIDATION FORM....
class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

            #  .... DATA FORM.....
class PersonCreationForm(forms.ModelForm):
    class Meta:
        model = Permode
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['datatype'].queryset = Datatype.objects.none()

        if 'network' in self.data:
            try:
                network_id = int(self.data.get('network'))
                self.fields['datatype'].queryset = Datatype.objects.filter(network_id=network_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['datatype'].queryset = self.instance.network.datatype_set.order_by('name')


        if 'datatype' in self.data:
            try:
                datatype_id = int(self.data.get('datatype'))
                self.fields['datatype'].queryset = Datatype.objects.filter(datatype_id=datatype_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['dataplan'].queryset = self.instance.datatype.dataplan_set.order_by('name')


        #  .... AIRTIME FORM....


class AirtimeForm(forms.ModelForm):
    class Meta:
        model = AirtimeTran
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['airtime'].queryset = Airtime.objects.all()

vtp/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
# from .decorators import unauthenticated_user, allowed_users
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout
from .forms import CreateUserForm

from .forms import PersonCreationForm, AirtimeForm
from .models import Permode, Datatype, Dataplan




        #   ....USER VALIDATION....

# @unauthenticated_user
def register(request):
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			user= form.save()
			form.save()

			username = form.cleaned_data.get('username')


			messages.success(request, username + ' Account created Successfully...')
			return redirect ('login')

	context = {'form':form}
	return render(request, 'vtp/register.html', context)



def login(request):

	if request.method == 'POST': 
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(request, username=username, password=password)

		if user is not None:
			auth_login(request, user)
			return redirect('dashboard')
		
		else: messages.info(request, 'Username OR Password is incorect')

	context = {}
	return render(request, 'vtp/login.html',context)
    
@login_required(login_url='login')
def logoutUser(request):
	logout(request)
	return redirect('login')


# def login(request):
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             auth_login(request, user)  # Use the auth_login function
#             return redirect('dashboard')
#         else:
#             messages.info(request, 'Username OR Password is incorrect')
#     context = {}
#     return render(request, 'vtp/login.html',context)



@login_required(login_url='login')
def dashboard(request):
 
	context = {}
	return render(request, 'vtp/dashboard.html', context)



def dataform(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dataform')
    return render(request, 'vtp/dataform.html', {'form': form})


@login_required(login_url='login')
def person_update_view(request, pk):
    permode = get_object_or_404(Permode, pk=pk)
    form = PersonCreationForm(instance=permode)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=permode)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'vtp/dataform.html', {'form': form})


# AJAX
@login_required(login_url='login')
def datatypes(request):
    network_id = request.GET.get('network_id')
    datatypes = Datatype.objects.filter(network_id=network_id).all()
    print(list(datatypes.values('id', 'name')))
    # return render(request, 'vtp/datadd.html', {'datatypes': datatypes})
    return JsonResponse(list(datatypes.values('id', 'name')), safe=False)

@login_required(login_url='login')
def dataplan(request):
    datatype_id = request.GET.get('datatype_id')
    dataplan = Dataplan.objects.filter(datatype_id=datatype_id).all()
    print(list(dataplan.values('id', 'name')))
    # return render(request, 'vtp/datadd.html', {'datatypes': datatypes})
    return JsonResponse(list(dataplan.values('id', 'name')), safe=False)



        # ....AIRTIME VIEW....

@login_required(login_url='login')
def airtimeform(request):
    form = AirtimeForm()
    if request.method == 'POST':
        form = AirtimeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('airtime')
    return render(request, 'vtp/airtimeform.html', {'form': form})

vtp/templates/vtp/airtimeform.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>....</title>
</head>
<body>
<h2>BUY AIRTIME</h2>

<form method="post" id="AirtimeForm" data-datatypes-url="{% url 'airtimeform' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>



</body>
</html>

vtp/templates/vtp/dashboard.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/svg-with-js.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css">
	
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    {% block content %}

<div class="services">

    <div class="container" style="display: flex; gap: 15px;">
        <div class="calinfo" style="flex: 1; text-align: center; background: #333; padding: 15px; border-radius: 8px;">
            <h4 style="color: #f0f4fa; font-size: 28px;">BAL: #2,000</h4>
        </div>
    
        <div class="calinfo" style="flex: 1; text-align: center; background: #333; padding: 15px; border-radius: 8px;">
           <a href="/dashboard">

            <i class="fas fa-tachometer-alt" style="color: #f0f4fa; font-size: 28px;"></i> 
           </a> <!-- Dashboard icon -->
        </div>
    </div>
    



    <div class="contain">
        <a href="" style="margin-right: 45px;">
        <div style="margin: 12px 12px 15px 12px;">
        <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                <div style="padding: 9px 22px 8px 22px;">
                <i class="fa-solid fa-money-check-dollar fa-6x" style="color: #0747b6;"></i>
                <h4 style="margin-top: 16px; font-size: 25px;">Fund Wallet</h4>
                </div>
        </button>
        </div>
        </a>

        <a href="{% url 'dataform' %}">
            <div style="margin: 12px 12px 15px 12px;">
            <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                    <div style="padding: 9px 22px 8px 22px;">
                    <i class="fa-solid fa-signal fa-6x" style="color: #0747b6;"></i>
                    <h4 style="margin-top: 16px; font-size: 25px;">Data</h4>
                    </div>
            </button>
            </div>
            </a>

            <a href="" style="margin-left: 45px;">
                <div style="margin: 12px 12px 15px 12px;">
                <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                        <div style="padding: 9px 22px 8px 22px;">
                        <i class="fa-solid fa-layer-group fa-6x" style="color: #0747b6;"></i>
                        <h4 style="margin-top: 16px; font-size: 25px;">Transactions</h4>
                        </div>
                </button>
                </div>
                </a>

        </button>
    </div>

    <div class="contain">
        <a href="{% url 'airtimeform' %}" style="margin-right: 45px;">
        <div style="margin: 12px 12px 15px 12px;">
        <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                <div style="padding: 9px 22px 8px 22px;">
                <i class="fa-solid fa-phone-volume fa-6x" style="color: #0747b6;"></i>
                <h4 style="margin-top: 16px; font-size: 25px;">Airtime</h4>
                </div>
        </button>
        </div>
        </a>

        <a href="">
            <div style="margin: 12px 12px 15px 12px;">
            <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                    <div style="padding: 9px 22px 8px 22px;">
                    <i class="fa-solid fa-wand-magic-sparkles fa-6x" style="color: #0747b6;"></i>
                    <h4 style="margin-top: 16px; font-size: 25px;">Electricity</h4>
                    </div>
            </button>
            </div>
            </a>

            <a href="" style="margin-left: 45px;">
                <div style="margin: 12px 12px 15px 12px;">
                <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                        <div style="padding: 9px 22px 8px 22px;">
                        <i class="fa-solid fa-book-open-reader fa-6x" style="color: #0747b6;"></i>
                        <h4 style="margin-top: 16px; font-size: 25px;">Result Checker</h4>
                        </div>
                </button>
                </div>
                </a>

        </button>
    </div>

    <div class="contain">
        <a href="" style="margin-right: 45px;">
        <div style="margin: 12px 12px 15px 12px;">
        <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                <div style="padding: 9px 22px 8px 22px;">
                <i class="fa-solid fa-print fa-6x" style="color: #0747b6;"></i>
                <h4 style="margin-top: 16px; font-size: 25px;">Paper Card</h4>
                </div>
        </button>
        </div>
        </a>

        <a href="">
            <div style="margin: 12px 12px 15px 12px;">
            <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                    <div style="padding: 9px 22px 8px 22px;">
                    <i class="fa-solid fa-right-left fa-6x" style="color: #0747b6;"></i>
                    <h4 style="margin-top: 16px; font-size: 25px;">Airtime-Cash</h4>
                    </div>
            </button>
            </div>
            </a>

            <a href="" style="margin-left: 45px;">
                <div style="margin: 12px 12px 15px 12px;">
                <button style="border: white; border-radius: 15%;background-color: #f0f4fa;">
                        <div style="padding: 9px 22px 8px 22px;">
                        <i class="fa-solid fa-tv fa-6x" style="color: #0747b6;"></i>
                        <h4 style="margin-top: 16px; font-size: 25px;">TV Sub</h4>
                        </div>
                </button>
                </div>
                </a>

        </button>
    </div>

</div>


<div style="margin: 7px 0px 0px 35px;">
<marquee bgcolor="#f0f4fa" loop="-1" scrollamounts="5" width="90%"> <p style="font-size: 25px;"> Welcome to wise choice construction company, our trusted partner for innovative and sustainable biogas, biodigester, and plumbing solutions.</p>
</marquee>
</div>

    <div class="chat">
        <a href="/">
        <div class="contain">
            <div style="margin: 0px 80px 2px -12px;">
            <button style="width: 120px; height: 90px; border: white; border-radius: 5%; background-color: #f0f4fa;">
                <div style="padding: 9px 15px 8px 15px;">
                    <i class="fa-brands fa-square-whatsapp fa-fade fa-5x" style="color: #0747b6;"></i>
                    <h4 style="margin-top: 10px; color: #f0f4fa; font-size: 25px;">Platform</h4>
                    </div>
            </button>
            </div>
            </a>

            <a href="/">
            <div style="margin: 0px 2px 2px 20px;">
                <button style="width: 120px; height: 90px; border: white; border-radius: 5%; background-color: #f0f4fa;">
                    <div style="padding: 9px 15px 8px 15px;">
                        <i class="fa-brands fa-square-whatsapp fa-fade fa-5x" style="color: #0747b6;"></i>
                        <h4 style="margin-top: 10px; font-size: 25px; color: #f0f4fa;">Chat Us</h4>
                        </div>
                </button>
                </div>
                </a>

            
        </div>
    </div>
    
    {% endblock content %}

vtp/templates/vtp/dataform.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>....</title>
</head>
<body>
<h2>BUY DATA</h2>

<form method="post" id="personForm" data-datatypes-url="{% url 'ajax_load_datatypes' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_network").change(function () {
        const url = $("#personForm").attr("data-datatypes-url");
        const networkId = $(this).val();  

        $.ajax({                      
            url: url,                    
            data: {
                'network_id': networkId       
            },
            success: function (data) {   
                // $("#id_datatype").html(data); 
                

                let html_data = '<option value="">---------</option>';
                data.forEach(function (datatype) {
                    html_data += `<option value="${datatype.id}">${datatype.name}</option>`
                });
                console.log(html_data);
                $("#id_datatype").html(html_data);

            }
        });



        $.ajax({                      
            url: url,                    
            data: {
                'datatype_id': datatypeId       
            },
            success: function (data) {   
                // $("#id_datatype").html(data); 
                

                let html_data = '<option value="">---------</option>';
                data.forEach(function (dataplan) {
                    html_data += `<option value="${dataplan.id}">${dataplan.name}</option>`
                });
                console.log(html_data);
                $("#id_dataplan").html(html_data);

            }
        });




    });
</script>

</body>
</html>

vtp/templates/vtp/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

	

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

				</div>

                {% for message in messages %}
                   <p id='messages'>{{message}}</p>
                {% endfor %}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'register' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

vtp/templates/vtp/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">






	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>

                {{form.errors}}
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'login' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>